# Generated by Django 2.0 on 2019-08-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
    ]
