# Generated by Django 2.0 on 2019-08-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_appointment_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Stats'),
        ),
    ]
